### ISSUE TITLE
Feature Request: Add custom strings to the semver calculation

### ISSUE THREAD

**Issue by vyas-n** [ietf-tools/semver-action#19]
Hello,

Thanks for the cool GitHub Action. I'm currently using this to tag repositories automatically and was wondering if there could be a feature to add a custom commit message into the SemVer calculation.

I'd like to calculate the next expected SemVer for a PR based on the PR title when I squash-merge the PR into the main branch. This is so that I can enforce that the tag version in the manifests are updated correctly before merging the PR.

Examples:

```yaml
- name: Get Next Semantic Version
  id: semver
  uses: ietf-tools/semver-action@v1
    token: ${{ github.token }}
    branch: main
    additionalCommits:
      - "ci: add something to ci"
- name: Check if tag matches version in files
  run: |
    [[ $(yq e '.version' Chart.yaml) == "${{ steps.semver.outputs.nextStrict }}" ]]
    [[ $(yq e '.appVersion' Chart.yaml) == "${{ steps.semver.outputs.nextStrict }}" ]]
```

```yaml
- name: Get Next Semantic Version
  id: semver
  uses: ietf-tools/semver-action@v1
    token: ${{ github.token }}
    branch: main
    additionalCommits:
      - ${{ github.event.pull_request.title }}
- name: Check if tag matches version in files
  run: |
    [[ $(yq e '.version' Chart.yaml) == "${{ steps.semver.outputs.nextStrict }}" ]]
    [[ $(yq e '.appVersion' Chart.yaml) == "${{ steps.semver.outputs.nextStrict }}" ]]
```
