### ISSUE TITLE
action always selects latest tag regardless of branch

### ISSUE THREAD

**Issue by jeacott1** [ietf-tools/semver-action#29]
using the following config
```
Run ietf-tools/semver-action@v1.[4]
  with:
    token: ***
    branch: main
    patchAll: true
    skipInvalidTags: true
    minorList: feat, feature
    patchList: fix, bugfix, perf, refactor, test, tests
    noVersionBumpBehavior: error
```

I have 2 branches, main, and a release/xxx branch
the latest tag on main is 0.3.0
the latest tag on release/xxx is 0.3.0-testing-p1

I have configured branch: main and expect tags to be found on main only.

the action outputs logs:
Comparing against latest tag: 0.3.0-testing-p1
>>> Will bump version 0.3.0-testing-p1 using PATCH
Current version is 0.3.0-testing-p1
Next version is v0.3.0

why is ietf-tools/semver-action comparing tags in different branches? this seems wrong and quite dangerous to me.
am I missing something?
