### ISSUE TITLE
Incorrect error: Couldn't find any commits between HEAD and latest tag.

### ISSUE THREAD

**Issue by johnburbridge** [ietf-tools/semver-action#38]
## Scenario
I'm working in a monorepo using a prefix for each service that needs a separate version / tag. I'm just getting started so there's only 1 service (`echo-api`) and 2 tags (`echo-api/v0.0.2` and`echo-api/v1.0.0`). 

I created the tag `echo-api/v0.0.2` manually so that semver-action would have a starting point. I configured the `prefix` parameter with `echo-api/` then committed a breaking change and it correctly bumped the version to `echo-api/v1.0.0`.

I made a few more configuration changes as follows:
```yaml
...
jobs:
  check:
    runs-on: ubuntu-latest # [ self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
        id: checkout
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          prefix: echo-api/
          noVersionBumpBehavior: warn
```
Which yileds the following:
![image](https://github.com/ietf-tools/semver-action/assets/830112/9de3ba9b-32df-4adf-984a-74c4004f79dc)

Given the above configuration, I would have expected the workflow to warn rather than error (similar to https://github.com/ietf-tools/semver-action/issues/34). 

When comparing HEAD to the tag:
```shell
$ git log HEAD...'echo-api/v1.0.0' --pretty=oneline
```
Which correctly returns:
```text
4e237553b5914971eb647d4780f2572ccf2425cb (HEAD -> feature/filter-echo-api-paths, origin/feature/filter-echo-api-paths) refactor: replacing markdown generator
f89f3ab63311605cb902a89316835a6eb16ba9f9 fix: deleting old generic workflows
dec45498a7ef80a58606e023f8956bda70a8a6e9 feat: refactoring and filtering workflows for echo-api
76411b9c936ad23d59c4981e6f2e67f5516ecf27 chore: adding echo-api README.md
```
I have no idea why this worked for the first test release and now is failing. Thoughts?

**Comment by NGPixel** [comment]
The error message is a bit misleading. You should compare against the "main" branch, not HEAD:

https://github.com/ietf-tools/semver-action/blob/fc64c94a8d52cc1da776770e72a1a053d5e83fd5/index.js#L135

**Comment by johnburbridge** [comment]
That makes sense, of course. So on a pull request branch that should really be as follows:
```yaml
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          branch: ${{ github.event.pull_request.head.ref }}
          prefix: ${{ env.VERSION_TAG_PREFIX }}
          noVersionBumpBehavior: warn
```
Thanks @NGPixel! Much appreciated.
